### ISSUE TITLE
Unable to download from pan.baidu cannot create account

### ISSUE THREAD

**Issue by amjadtbssm** [scarsty/kys-pascal#4]
I am unable to download the bin files from the link provided as baidu account can only be created using inland china numbers only please upload files to another server or here on github as release files.

**Comment by scarsty** [comment]
[kys-win原版复刻.zip](https://github.com/scarsty/kys-pascal/files/3700441/kys-win.zip)

**Comment by scarsty** [comment]
You'd better to compile the kys.exe yourself to run it.

**Comment by amjadtbssm** [comment]
Thanks a ton @scarsty, Appreciate your help
